### ISSUE TITLE
论文中的结果和您实现的结果相差好大

### ISSUE THREAD

**Issue by michealowen** [InkCoderYmc/STRNN-change#1]

**Comment by InkCoderYmc** [comment]
这个是我在我个人数据集上进行了修改，原模型不是这个。你可以找一下原模型的复现-------- 原始邮件 --------发件人： michealowen <notifications@github.com>日期： 2021年3月2日周二 15:10收件人： InkCoderYmc/STRNN-change <STRNN-change@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [InkCoderYmc/STRNN-change] 论文中的结果和您实现的结果相差好大 (#1)

**Comment by michealowen** [comment]
> 这个是我在我个人数据集上进行了修改，原模型不是这个。你可以找一下原模型的复现-------- 原始邮件 --------发件人： michealowen <notifications@github.com>日期： 2021年3月2日周二 15:10收件人： InkCoderYmc/STRNN-change <STRNN-change@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主 题： [InkCoderYmc/STRNN-change] 论文中的结果和您实现的结果相差好大 (#1) —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

您的实现是克隆自https://github.com/yongqyu/STRNN.git这个仓库么？我发现结果是一样的

**Comment by InkCoderYmc** [comment]
是克隆的，根据自身工作进行修改后并未修改主页，不确定是不是你发的连接，你可以尝试着再找一下

**Comment by michealowen** [comment]
> 是克隆的，根据自身工作进行修改后并未修改主页，不确定是不是你发的连接，你可以尝试着再找一下

好的，多谢指点。
